@host = http://localhost:8080

### Typed Client with Interface

GET {{host}}/typed-with-interface/posts
Content-Type: application/json


### Typed Client

GET {{host}}/typed/posts
Content-Type: application/json


### Named Client

GET {{host}}/named/posts
Content-Type: application/json


### Factory Client

GET {{host}}/factory/posts
Content-Type: application/json
